### ISSUE TITLE
Xamarin PCL support

### ISSUE THREAD

**Issue by MitchMilam** [mj1856/NodaTime.NetworkClock#1]
Great work here.  I am working with Xamarin Forms which allows us to develop for iOS, Android, and Windows Phone.
It seems that Windows Phone doesn't support System.Net.Sockets.  
Do you have any plans to find a way around that?

Thanks, Mitch

**Comment by mattjohnsonpint** [comment]
I hadn't really considered it, but a quick search found [this project](https://github.com/rdavisau/sockets-for-pcl) for supporting sockets from a PCL.  I'd want to explore it a bit more before taking a dependency though.

Out of curiosity - what is the use case that NTP is needed on a phone app?  Are you concerned with clock tampering?  Or something else?

**Comment by mattjohnsonpint** [comment]
I spent a bit of time on this tonight.  The [sockets-for-pcl](https://github.com/rdavisau/sockets-for-pcl) library will work nicely, though I need to rework some of the internals fo proper async implementation.  I should be able to have a new version out in the next couple of days.

**Comment by MitchMilam** [comment]
@mj1856 maybe this will help.  https://github.com/MitchMilam/NTPClient

**Comment by mattjohnsonpint** [comment]
Sorry for the delay, this is still on my radar but I've been tied up with a few other things.

**Comment by mattjohnsonpint** [comment]
Since the world has changed a bit since this was opened, I'm going to close this issue.

The current 2.0.0 version targets .NET Standard 1.3, which is compatible with Xamarin.iOS 10.0 and Xamarin.Android 7.0, according to the chart [here](https://docs.microsoft.com/en-us/dotnet/articles/standard/library).

Thanks.
