### ISSUE TITLE
Unhandled exception in NodaTime.NetworkClock after updating to NodaTime 2.0

### ISSUE THREAD

**Issue by jshergal** [mj1856/NodaTime.NetworkClock#4]
I recently upgraded my project to NodaTime 2.0 and found that now NodaTime.NetworkClock is throwing an unhandled exception.  I am assuming this is related to changes in the API of NodaTime.

Exception:
Method 'GetCurrentInstant' in type 'NodaTime.NetworkClock' from assembly 'NodaTime.NetworkClock, Version=1.1.0.60, Culture=neutral, PublicKeyToken=null' does not have an implementation.

In NodaTime 2.0 the IClock interface has changed. Instead of a `Now` property, there is now a method `GetCurrentInstant()`

**Comment by mattjohnsonpint** [comment]
Yep, I need to update for 2.0.  Thanks for the reminder.

**Comment by jshergal** [comment]
I have the change. I will try to make a pull request - I am new to Git.  I have used RC, CVS, SVN, Mercurial and TFS, but never GIT :)  FYI - the update requires moving to .Net 4.5 as NodaTime required that change. I am assuming this would be acceptable.

**Comment by mattjohnsonpint** [comment]
Thanks for the offer, but I'd prefer to take this one. I want to rework this for .NET Standard.  I started doing this in some of my other libraries and want to take a uniform approach.

**Comment by mattjohnsonpint** [comment]
Updated.  Please use version 2.0.0 and let me know if you have any issues.  Thanks.
